### ISSUE TITLE
ZC Crashes without libzcsound.dll

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#82] opened 2017-06-12 22:43 UTC
Rather than giving an error/warning, and cleanly exiting, ZC outright crashes immediately after passing the title screen (Zelda Classic logo, not AGN flame banner) if the file libzcsound.dll is not present.

It is likely missing a check for the file before doing things that need it. This may also be true for other files, but I'm rather certain that without the allegro libs, ZC won;t run at all, so it cannot crash.

These should be output when compiling, but they are not; and libzcsound.dll is not present in the package (under /bin, with the allegro libs).

**Comment by evouga** [comment] 2017-06-13 02:48
There is no libzcsound.dll. All the sound code is now compiled into a static library (zcsound.lib) and linked in to ZC and ZQ at compile time.

Are you sure you didn't accidentally muck up the compile settings of ZC and/or the sound library?

**Comment by Gleeok** [comment] 2017-06-13 04:16
zcsound.dll is from before ZC went open source with GPL. The libraries it uses were LGPL'd, so it was necessary to not voilate any 3rd party licenses. However, zcsound.lib can just be static linked now with no issue (or even compiled directly as a cpp file into the executables)

**Comment by evouga** [comment] 2017-06-13 06:15
If you need help adjusting something in the CMake configuration, let me know and I will do it for you.

Moving back to each developer maintaining their own (constantly broken/out of sync) set of build scripts is about as crazy as moving back to emailing source code back and forth instead of using version control. And it's a huge hurdle to anybody trying to join or help out in the future if they can't easily get the code to compile.

**Comment by Gleeok** [comment] 2017-06-13 07:16
Also forgot to mention: The ZCM_DLL macro controls whether it's compiled as a dll, so make sure you are not manually defining this (anywhere). 

If you are not sure you are no longer defining this and want absolute confirmation this is not the case you can go to (in VS2008)[Config(eg;debug/release)]->cpp_source_properties->output_preprocessed_file, and there should be no __declspec(dllimport)/__declspec(dllexport) decorators in the zcmusic section.

Not sure if this helps but let us know what the problem is/was.

**Comment by evouga** [comment] 2017-06-15 19:46
Closing this issue as I don't see how this problem can arise from a fresh copy of the current code.

Zoria, if you need help resolving this problem, feel free to ask on Skype.

**Closed as completed by evouga** 2017-06-15 19:46 UTC
