### ISSUE TITLE
ZQuest: Windows 10 Fullscreen Issues Reported

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#75] opened 2017-06-07 05:12 UTC
ZQuest is going to need a 24b double-blit, just as ZC has.

**Comment by evouga** [comment] 2017-06-07 05:32
Can you elaborate? As far as I know there is currently no difference between ZC and ZQ's backend graphics code, other than the list of supported resolutions.

**Comment by evouga** [comment] 2017-06-11 04:54
Closing pending a more specific report of what the issue is.

**Closed as completed by evouga** 2017-06-11 04:54 UTC
